### ISSUE TITLE
Three failing tests.

### ISSUE THREAD

**Issue by conzo77** [jamesnetherton/lolcat4j#9]
I cloned the git repository and ran a standard mvn clean test.

Three tests fail:
com.github.jamesnetherton.lolcat4j.internal.console.ConsolePainterTest#testNonAnimatedOutput
com.github.jamesnetherton.lolcat4j.internal.console.ConsolePainterTest#testStripAnsi
com.github.jamesnetherton.lolcat4j.internal.console.ConsolePainterTest#testStripTabs

In comparison with the expected output, the code seems to insert an extra line after each line matchin the expected input.

Example for  com.github.jamesnetherton.lolcat4j.internal.console.ConsolePainterTest#testNonAnimatedOutput:

`[38;5;164ml[0m[38;5;63m
[0m[38;5;44m
[0m[38;5;83mo[0m[38;5;184m
[0m[38;5;203m
[0m[38;5;163ml[0m[38;5;93m
[0m[38;5;39m
[0m[38;5;48mc[0m[38;5;154m
[0m[38;5;208m
[0m[38;5;199ma[0m[38;5;93m
[0m[38;5;33m
[0m[38;5;49mt[0m[38;5;118m
[0m[38;5;214m
[0m`

I imported the project in Intellij 2020.3.2 Ultimate and ran maven from there. OS is Windows 10. Maven is bundled Maven 3

The code itself seems to work fine, it's just these three tests that fail.

My apologies if I overlooked something obvious.

**Comment by conzo77** [comment]
![image](https://user-images.githubusercontent.com/63388169/123263374-2e14ea80-d4f9-11eb-9474-848a8cfea4fc.png)

**Comment by jamesnetherton** [comment]
Maybe [here](https://github.com/jamesnetherton/lolcat4j/blob/master/src/test/java/com/github/jamesnetherton/lolcat4j/internal/console/utils/LoggingPrintStream.java#L40) instead of hard coding `\n` it should use `System.lineSeparator()`.

Or it could be that the content in `animatedExpected.txt` is only suitable for *nix based systems. I never considered Windows much when I started the project TBH.

**Comment by conzo77** [comment]
Thanks for your quick response. I'll try out your suggestion. It makes sense - and yeah, there are issues like this that are both annoying and easy to forget if you primarly work on *nix. 

I'll report back when I've had a chance to try it out.

**Comment by conzo77** [comment]
Regrettably, it didn't fix the problem. The error is the same. It could still be a windows related problem, though - at least it smells like that.

**Comment by jamesnetherton** [comment]
Bit late - but I finally fixed this. Also added a Windows to the CI workflow to verify.

**Comment by conzo77** [comment]
Thanks! I had a quick look at the updated code, but weirdly I still have test fails. I'll have to take a better look though, so for now please take this strictly fyi.
